services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=db'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USER}'
    ports:
      - '5432:5432'
